version: "3.8"

services:
    app:
        networks:
            - network-laravel
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./:/project
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: db_project
            DB_USERNAME: user1
            DB_PASSWORD: user1password
        command: sh -c "composer install && php artisan migrate && php artisan serve --host 0.0.0.0 --port 8000 "

    db:
        networks:
            - network-laravel
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: db_project
            MYSQL_USER: user1
            MYSQL_PASSWORD: user1password
        ports:
            - "3340:3306"
        volumes:
            - type: volume
              source: db-data-biblioteca
              target: /var/lib/mysql

volumes:
    db-data-biblioteca:

networks:
    network-laravel:
